name = "OneLayer"
uuid = "bca00d65-5e4e-4fb8-bc00-c8dd8e177256"
authors = ["radni <amirhossein_kh@ymail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
